# ╔══════════════════════════════════════════════╗
# ║ This file is only read once per server start.║
# ║ Restart server when changed!                 ║
# ╚══════════════════════════════════════════════╝

# Site settings
# ─────────────
baseurl: /1718-webdev2-project # the subpath of your site, e.g. /blog
# host : 127.0.0.1
# port : 4000

# Custom Site variables
# ─────────────────────
title: Web Development II

# Build settings
# ──────────────
defaults:

exclude:
  - Gemfile

plugins:
# - jekyll-feed
# - jekyll-gist
# - jekyll-mentions
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
  - jemoji

sass:
  style: nested
#  style: expanded
#  style: compact
#  style: compressed